FROM php:7.3-fpm

# 安装 PHP Redis、pdo_mysql 和 sockets 扩展
RUN pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pdo_mysql sockets pcntl

# 安装 libzip 开发包
RUN apt-get update && apt-get install -y libzip-dev

# 安装 PHP zip 扩展
RUN docker-php-ext-install zip

# 更新包列表并安装必要的工具，包括 procps 和 sudo
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-openssl-dev \
    pkg-config \
    git \
    unzip \
    procps \
    sudo  \
    python3 \
    python3-pip 

# 安装 PyPDF2
RUN pip3 install PyPDF2

# 更新 PECL 频道
RUN pecl channel-update pecl.php.net

# 安装 Swoole 4.x 版本
RUN pecl install swoole-4.8.11 \
    && docker-php-ext-enable swoole

# 安装 MongoDB PHP 扩展
RUN pecl channel-update pecl.php.net \
    && pecl install mongodb-1.10.0 \
    && docker-php-ext-enable mongodb

# 安装 Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# 设置工作目录
WORKDIR /var/www/html
