version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/vhost:/etc/nginx/vhost
      - D:/work:/var/www/html

  php7.3:
    build:
      context: .
      dockerfile: dockerfile-php7.3
    volumes:
      - D:/work:/var/www/html
  php7.4:
    build:
      context: .
      dockerfile: dockerfile-php7.4
    volumes:
      - D:/work:/var/www/html
  node:
    image: node:14.16
    volumes:
      - D:/work:/var/www/html
    ports:
      - "9527:9527"
      - "9528:9528"
    command: tail -f /dev/null  # 指定一个简单的命令来保持容器持续运行
