version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/vhost:/etc/nginx/vhost
      - D:/work:/var/www/html

  php:
    build:
      context: .
      dockerfile: docker-compose-php
    volumes:
      - D:/work:/var/www/html