version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/vhost:/etc/nginx/vhost
      - /Users/kenny/Desktop/work:/var/www/html
      - ./nginx/hosts:/etc/hosts-modification
    networks:
      app-network:
        ipv4_address: 172.23.0.4
    command: ["/bin/sh", "-c", "cat /etc/hosts-modification >> /etc/hosts && nginx -g 'daemon off;'"]

  php7.3:
    build:
      context: .
      dockerfile: dockerfile-php7.3
    volumes:
      - /Users/kenny/Desktop/work:/var/www/html
      - ./php73/hosts:/etc/hosts-modification:rw
    networks:
      app-network:
        ipv4_address: 172.23.0.5
    command: ["/bin/sh", "-c", "cat /etc/hosts-modification >> /etc/hosts && php-fpm"]

  node:
    image: node:14.16
    volumes:
      - /Users/kenny/Desktop/work:/var/www/html
      - ./php73/hosts:/etc/hosts-modification:rw
    ports:
      - "9527:9527"
      - "9528:9528"
    command: ["/bin/sh", "-c", "cat /etc/hosts-modification >> /etc/hosts && tail -f /dev/null"]
    networks:
      app-network:
        ipv4_address: 172.23.0.7

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16

volumes:
  mysql-data: