FROM php:7.3-fpm

# 更换为阿里云的 Debian 源并安装必要的包
RUN sed -i 's|http://deb.debian.org|http://mirrors.aliyun.com|g' /etc/apt/sources.list \
    && sed -i 's|http://security.debian.org|http://mirrors.aliyun.com|g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y \
        libzip-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        pkg-config \
        git \
        unzip \
        procps \
        sudo \
        python3 \
        python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 安装 PHP 扩展
RUN pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pdo_mysql sockets pcntl bcmath zip

# 安装 PyPDF2
RUN pip3 install PyPDF2

# 更新 PECL 频道并安装 Swoole
RUN pecl channel-update pecl.php.net \
    && pecl install swoole-4.8.11 \
    && docker-php-ext-enable swoole

# 安装 MongoDB PHP 扩展
RUN pecl install mongodb-1.6.0 \
    && docker-php-ext-enable mongodb

# 安装 Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# 设置工作目录
WORKDIR /var/www/html
