FROM php:7.4-fpm

# 安装 PHP Redis、pdo_mysql 和 sockets 扩展
RUN pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pdo_mysql sockets

# 安装 libzip 开发包
RUN apt-get update && apt-get install -y libzip-dev

# 安装 PHP zip 扩展
RUN docker-php-ext-install zip

# 安装 PHP GD 扩展所需的依赖库
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev

# 配置并安装 PHP GD 扩展
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

# 安装 Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
