version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/template:/etc/nginx/template
      - ./nginx/vhost:/etc/nginx/vhost
      - /Users/kenny/Desktop/work:/var/www/html
      - ./nginx/hosts:/etc/hosts-modification
      - ./nginx/start.sh:/start.sh
    environment:
      PHP_FPM_SERVICE: php-xdebug
    networks:
      app-network:
        ipv4_address: 172.23.0.4
    command: ["/bin/sh", "/start.sh"]

  php7.3:
    build:
      dockerfile: dockerfile-php7.3
    volumes:
      - /Users/kenny/Desktop/work:/var/www/html
      - ./php73/hosts:/etc/hosts-modification:rw
    ports:
      - "2346:2346"
    networks:
      app-network:
        ipv4_address: 172.23.0.5
    command: ["/bin/sh", "-c", "cat /etc/hosts-modification >> /etc/hosts && php-fpm"]

  php-xdebug:
    build:
      dockerfile: dockerfile-php73-xdebug
    volumes:
      - /Users/kenny/Desktop/work:/var/www/html
      - ./php73/hosts:/etc/hosts-modification:rw
      - ./php74/xdebug.log:/var/www/html/log/xdebug.log:rw
    environment:
      PHP_IDE_CONFIG: "serverName=php-cli" 
    networks:
      app-network:
        ipv4_address: 172.23.0.10
    command: ["/bin/sh", "-c", "cat /etc/hosts-modification >> /etc/hosts && php-fpm"]

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16

# volumes:
#   #mysql-data: