input {
  file {
    path => "/var/www/html/log/**/**/*.log" # 递归匹配变化的目录
    start_position => "beginning" # 从文件开始读取
    sincedb_path => "/dev/null" # 每次重启都重新读取
  }
}

filter {
  # 可以添加过滤器，例如解析日志格式
  grok {
    match => { "message" => "%{COMMONAPACHELOG}" } # 示例：Apache日志格式
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "log-%{+YYYY.MM.dd}" # 替换为你的索引名称
  }
}
