input {
  file {
    path => "/var/www/html/log/**/**/*.log"
    start_position => "beginning"
    sincedb_path => "/var/log/logstash/sincedb"
    sincedb_write_interval => 15
  }
}

filter {
  # 将 file 插件自带的 path 字段保留到 ES 文档里
  mutate {
    # 如果你不想修改原始 path 字段，可以复制到一个新字段，比如 log_path
    add_field => { "path" => "%{path}" }
  }
  
  grok {
    match => { "message" => "%{COMMONAPACHELOG}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "log-%{+YYYY.MM.dd}"
  }
}
