input {
  file {
    path => "/var/www/html/log/**/**/*.log" # 递归匹配动态目录
    start_position => "beginning" # 从文件的开头开始读取
    sincedb_path => "/var/log/logstash/sincedb" # 持久化文件，用于存储读取进度
    sincedb_write_interval => 15 # 每隔15秒写入一次当前读取的位置
  }
}

filter {
  # 添加过滤器，例如解析日志格式
  grok {
    match => { "message" => "%{COMMONAPACHELOG}" } # 示例：Apache日志格式
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "log-%{+YYYY.MM.dd}" # 替换为你的索引名称
  }
}
